namespace DiscWeave.Api.Features.Exports;

public sealed record ExportRestoreResponse(
    bool Restored,
    int FormatVersion,
    int Artists,
    int Labels,
    int Releases,
    int Tracks,
    int OwnedItems,
    int LocalAudioFiles,
    int DigitalTrackFileLinks,
    int Playlists,
    int Credits,
    int ArtistRelations,
    int TrackRelations,
    int Dictionaries,
    int ImportPatterns,
    int NamingProfiles,
    int TagRoleMappings,
    int TrackStackSettings,
    int TrackRelationParserRules,
    int ReleaseNamingOverrides,
    int RatingCriteria,
    int Ratings);
