import { describe, expect, it } from 'vitest'
import {
  defaultCatalogDictionaries,
  type ReleaseImportDraft,
} from '../catalog/catalogApi'
import { applyDiscogsReleaseToImportDraft } from './importDiscogsApply'

describe('applyDiscogsReleaseToImportDraft', () => {
  it('keeps Discogs track-specific credits while inheriting release artists for non-Various-Artists drafts', () => {
    const draft = applyDiscogsReleaseToImportDraft({
      artists: [],
      dictionaries: defaultCatalogDictionaries,
      groups: {
        artists: false,
        classification: false,
        core: false,
        labels: false,
        tracklist: true,
      },
      draft: {
        id: 'draft-1',
        sourcePath: '/Music/Release',
        relativePath: 'Release',
        status: 'needsReview',
        title: 'Local Release',
        type: 'album',
        catalogNumber: null,
        labelName: null,
        releaseDate: null,
        year: 1992,
        isVariousArtists: false,
        notOnLabel: true,
        artistNames: ['Robin S'],
        artistCredits: [
          { artistId: null, name: 'Robin S', role: 'mainArtist' },
        ],
        selectedArtistIds: [],
        artistSuggestions: [],
        labels: [],
        genres: [],
        tags: [],
        externalSources: [],
        coverPath: null,
        issues: [],
        tracks: [
          {
            id: 'track-1',
            filePath: '/Music/Release/01 Show Me Love.m4a',
            relativePath: '01 Show Me Love.m4a',
            format: 'm4a',
            sizeBytes: 100,
            lastModifiedAt: '2026-06-01T12:00:00Z',
            durationSeconds: 300,
            position: 1,
            disc: null,
            side: null,
            title: 'Show Me Love',
            artistNames: ['Robin S'],
            artistCredits: [],
            artistSuggestions: [],
            trackSuggestions: [],
            isSkipped: false,
            selectedTrackId: null,
            selectedArtistIds: [],
            inheritReleaseArtistCredits: false,
            issues: [],
          },
        ],
      },
      detail: {
        source: {
          providerName: 'discogs',
          resourceType: 'release',
          externalId: '123',
          sourceUrl: 'https://www.discogs.com/release/123',
          attribution: 'Data provided by Discogs.',
        },
        title: 'Show Me Love',
        artists: ['Robin S'],
        year: 1992,
        trackCount: 1,
        labels: ['Champion'],
        formats: ['Vinyl'],
        catalogNumber: 'CHAMP 12 300',
        barcodes: [],
        tracklist: [],
        identifiers: [],
        credits: [],
        draft: {
          title: 'Show Me Love',
          type: 'single',
          genres: ['House'],
          year: 1992,
          releaseDate: null,
          artistCredits: [{ name: 'Robin S', role: 'mainArtist' }],
          labels: [],
          tracklist: [
            {
              title: 'Show Me Love (Stonebridge Club Mix)',
              position: 1,
              disc: null,
              side: 'A',
              durationSeconds: 300,
              artistCredits: [{ name: 'StoneBridge', role: 'Remix' }],
            },
          ],
          externalSources: [
            {
              providerName: 'discogs',
              resourceType: 'release',
              externalId: '123',
              sourceUrl: 'https://www.discogs.com/release/123',
            },
          ],
        },
      },
    })

    expect(draft.tracks[0].artistCredits).toMatchObject([
      { name: 'StoneBridge', role: 'remixer' },
    ])
    expect(draft.tracks[0].inheritReleaseArtistCredits).toBe(true)
  })

  it('keeps local audio duration when Discogs track duration is missing', () => {
    const draft = applyDiscogsReleaseToImportDraft({
      artists: [],
      dictionaries: defaultCatalogDictionaries,
      groups: {
        artists: false,
        classification: false,
        core: false,
        labels: false,
        tracklist: true,
      },
      draft: {
        id: 'draft-1',
        sourcePath: '/Music/Release',
        relativePath: 'Release',
        status: 'needsReview',
        title: 'Local Release',
        type: 'single',
        catalogNumber: null,
        labelName: null,
        releaseDate: null,
        year: 1990,
        isVariousArtists: false,
        notOnLabel: true,
        artistNames: ['Robin Stone'],
        artistCredits: [
          { artistId: null, name: 'Robin Stone', role: 'mainArtist' },
        ],
        selectedArtistIds: [],
        artistSuggestions: [],
        labels: [],
        genres: [],
        tags: [],
        externalSources: [],
        coverPath: null,
        issues: [],
        tracks: [
          {
            id: 'track-1',
            filePath: '/Music/Release/01 Show Me Love (Montego Mix).flac',
            relativePath: '01 Show Me Love (Montego Mix).flac',
            format: 'flac',
            sizeBytes: 100,
            lastModifiedAt: '2026-06-01T12:00:00Z',
            durationSeconds: 336,
            position: 1,
            disc: null,
            side: null,
            title: 'Show Me Love (Montego Mix)',
            artistNames: ['Robin Stone'],
            artistCredits: [],
            artistSuggestions: [],
            trackSuggestions: [],
            isSkipped: false,
            selectedTrackId: null,
            selectedArtistIds: [],
            inheritReleaseArtistCredits: false,
            issues: [],
          },
        ],
      },
      detail: {
        source: {
          providerName: 'discogs',
          resourceType: 'release',
          externalId: '456',
          sourceUrl: 'https://www.discogs.com/release/456',
          attribution: 'Data provided by Discogs.',
        },
        title: 'Show Me Love',
        artists: ['Robin Stone'],
        year: 1990,
        trackCount: 1,
        labels: ['Champion'],
        formats: ['Vinyl'],
        catalogNumber: 'CHAMP 12 300',
        barcodes: [],
        tracklist: [],
        identifiers: [],
        credits: [],
        draft: {
          title: 'Show Me Love',
          type: 'single',
          genres: [],
          year: 1990,
          releaseDate: null,
          artistCredits: [{ name: 'Robin Stone', role: 'mainArtist' }],
          labels: [],
          tracklist: [
            {
              title: 'Show Me Love (Montego Mix)',
              position: 1,
              disc: null,
              side: 'A',
              durationSeconds: null,
              artistCredits: [],
            },
          ],
          externalSources: [],
        },
      },
    })

    expect(draft.tracks[0].durationSeconds).toBe(336)
  })

  it('turns matching Discogs track main artists into release artist inheritance', () => {
    const draft = applyDiscogsReleaseToImportDraft({
      artists: [],
      dictionaries: defaultCatalogDictionaries,
      groups: {
        artists: true,
        classification: true,
        core: false,
        labels: false,
        tracklist: true,
      },
      draft: {
        id: 'draft-1',
        sourcePath: '/Music/Release',
        relativePath: 'Release',
        status: 'needsReview',
        title: 'Local Release',
        type: 'album',
        catalogNumber: null,
        labelName: null,
        releaseDate: null,
        year: 1992,
        isVariousArtists: false,
        notOnLabel: true,
        artistNames: ['Robin S'],
        artistCredits: [
          { artistId: null, name: 'Robin S', role: 'mainArtist' },
        ],
        selectedArtistIds: [],
        artistSuggestions: [],
        labels: [],
        genres: [],
        tags: ['local-tag'],
        externalSources: [],
        coverPath: null,
        issues: [],
        tracks: [
          {
            id: 'track-1',
            filePath: '/Music/Release/01 Show Me Love.m4a',
            relativePath: '01 Show Me Love.m4a',
            format: 'm4a',
            sizeBytes: 100,
            lastModifiedAt: '2026-06-01T12:00:00Z',
            durationSeconds: 300,
            position: 1,
            disc: null,
            side: null,
            title: 'Show Me Love',
            artistNames: ['Robin S'],
            artistCredits: [],
            artistSuggestions: [],
            trackSuggestions: [],
            isSkipped: false,
            selectedTrackId: null,
            selectedArtistIds: [],
            inheritReleaseArtistCredits: false,
            issues: [],
          },
        ],
      },
      detail: {
        source: {
          providerName: 'discogs',
          resourceType: 'release',
          externalId: '123',
          sourceUrl: 'https://www.discogs.com/release/123',
          attribution: 'Data provided by Discogs.',
        },
        title: 'Show Me Love',
        artists: ['Robin S'],
        year: 1992,
        trackCount: 1,
        labels: ['Champion'],
        formats: ['Vinyl'],
        catalogNumber: 'CHAMP 12 300',
        barcodes: [],
        tracklist: [],
        identifiers: [],
        credits: [],
        draft: {
          title: 'Show Me Love',
          type: 'single',
          genres: ['Genre House', 'Garage House'],
          year: 1992,
          releaseDate: null,
          artistCredits: [{ name: 'Robin S', role: 'mainArtist' }],
          labels: [],
          tracklist: [
            {
              title: 'Show Me Love (Stonebridge Club Mix)',
              position: 1,
              disc: null,
              side: 'A',
              durationSeconds: 300,
              artistCredits: [
                { name: 'Robin S', role: 'mainArtist' },
                { name: 'StoneBridge', role: 'Remix' },
              ],
            },
          ],
          externalSources: [
            {
              providerName: 'discogs',
              resourceType: 'release',
              externalId: '123',
              sourceUrl: 'https://www.discogs.com/release/123',
            },
          ],
        },
      },
    })

    expect(draft.isVariousArtists).toBe(false)
    expect(draft.genres).toEqual(['House', 'Garage House'])
    expect(draft.tags).toEqual(['local-tag'])
    expect(draft.tracks[0].inheritReleaseArtistCredits).toBe(true)
    expect(draft.tracks[0].artistCredits).toMatchObject([
      { name: 'StoneBridge', role: 'remixer' },
    ])
  })

  it('keeps overlapping Discogs track main artists explicit for Various Artists drafts', () => {
    const draft = applyDiscogsReleaseToImportDraft({
      artists: [],
      dictionaries: defaultCatalogDictionaries,
      groups: {
        artists: true,
        classification: false,
        core: false,
        labels: false,
        tracklist: true,
      },
      draft: {
        id: 'draft-1',
        sourcePath: '/Music/Release',
        relativePath: 'Release',
        status: 'needsReview',
        title: 'Local Release',
        type: 'album',
        catalogNumber: null,
        labelName: null,
        releaseDate: null,
        year: 1992,
        isVariousArtists: false,
        notOnLabel: true,
        artistNames: ['Robin S'],
        artistCredits: [
          { artistId: null, name: 'Robin S', role: 'mainArtist' },
        ],
        selectedArtistIds: [],
        artistSuggestions: [],
        labels: [],
        genres: [],
        tags: [],
        externalSources: [],
        coverPath: null,
        issues: [],
        tracks: [
          {
            id: 'track-1',
            filePath: '/Music/Release/01 Show Me Love.m4a',
            relativePath: '01 Show Me Love.m4a',
            format: 'm4a',
            sizeBytes: 100,
            lastModifiedAt: '2026-06-01T12:00:00Z',
            durationSeconds: 300,
            position: 1,
            disc: null,
            side: null,
            title: 'Show Me Love',
            artistNames: ['Robin S'],
            artistCredits: [],
            artistSuggestions: [],
            trackSuggestions: [],
            isSkipped: false,
            selectedTrackId: null,
            selectedArtistIds: [],
            inheritReleaseArtistCredits: false,
            issues: [],
          },
          {
            id: 'track-2',
            filePath: '/Music/Release/02 Other.m4a',
            relativePath: '02 Other.m4a',
            format: 'm4a',
            sizeBytes: 100,
            lastModifiedAt: '2026-06-01T12:00:00Z',
            durationSeconds: 300,
            position: 2,
            disc: null,
            side: null,
            title: 'Other',
            artistNames: ['Other Artist'],
            artistCredits: [],
            artistSuggestions: [],
            trackSuggestions: [],
            isSkipped: false,
            selectedTrackId: null,
            selectedArtistIds: [],
            inheritReleaseArtistCredits: false,
            issues: [],
          },
        ],
      },
      detail: {
        source: {
          providerName: 'discogs',
          resourceType: 'release',
          externalId: '123',
          sourceUrl: 'https://www.discogs.com/release/123',
          attribution: 'Data provided by Discogs.',
        },
        title: 'Show Me Love',
        artists: ['Robin S'],
        year: 1992,
        trackCount: 2,
        labels: [],
        formats: [],
        catalogNumber: null,
        barcodes: [],
        tracklist: [],
        identifiers: [],
        credits: [],
        draft: {
          title: 'Show Me Love',
          type: 'single',
          genres: [],
          year: 1992,
          releaseDate: null,
          artistCredits: [{ name: 'Robin S', role: 'mainArtist' }],
          labels: [],
          tracklist: [
            {
              title: 'Show Me Love',
              position: 1,
              disc: null,
              side: 'A',
              durationSeconds: 300,
              artistCredits: [{ name: 'Robin S', role: 'mainArtist' }],
            },
            {
              title: 'Other',
              position: 2,
              disc: null,
              side: 'B',
              durationSeconds: 300,
              artistCredits: [{ name: 'Other Artist', role: 'mainArtist' }],
            },
          ],
          externalSources: [],
        },
      },
    })

    expect(draft.isVariousArtists).toBe(true)
    expect(draft.tracks[0].inheritReleaseArtistCredits).toBe(false)
    expect(draft.tracks[0].artistCredits).toMatchObject([
      { name: 'Robin S', role: 'mainArtist' },
    ])
  })

  it('keeps Discogs sourced same-name artists unselected when no matching source exists', () => {
    const draft = applyDiscogsReleaseToImportDraft({
      artists: [
        {
          id: 'local-robin-stone',
          name: 'Robin Stone',
          type: 'Person',
          aliases: [],
          members: [],
          relationHint: '',
          creditHint: '',
          relations: [],
          credits: [],
          tags: [],
          summary: '',
          externalSources: [],
        },
      ],
      dictionaries: defaultCatalogDictionaries,
      groups: {
        artists: true,
        classification: false,
        core: false,
        labels: false,
        tracklist: false,
      },
      draft: baseDraft(),
      detail: {
        source: {
          providerName: 'discogs',
          resourceType: 'release',
          externalId: '123',
          sourceUrl: 'https://www.discogs.com/release/123',
          attribution: 'Data provided by Discogs.',
        },
        title: 'Show Me Love',
        artists: ['Robin Stone'],
        year: 1993,
        trackCount: 1,
        labels: [],
        formats: [],
        catalogNumber: null,
        barcodes: [],
        tracklist: [],
        identifiers: [],
        credits: [],
        draft: {
          title: 'Show Me Love',
          type: 'single',
          genres: [],
          year: 1993,
          releaseDate: null,
          artistCredits: [
            {
              name: 'Robin Stone',
              role: 'mainArtist',
              externalSource: {
                providerName: 'discogs',
                resourceType: 'artist',
                externalId: '111',
                sourceUrl: 'https://www.discogs.com/artist/111',
              },
            },
          ],
          labels: [],
          tracklist: [],
          externalSources: [],
        },
      },
    })

    expect(draft.artistCredits).toMatchObject([
      {
        artistId: null,
        name: 'Robin Stone',
        role: 'mainArtist',
        externalSource: { externalId: '111' },
      },
    ])
    expect(draft.selectedArtistIds).toEqual([])
  })

  it('matches Discogs sourced artists by source identity ignoring provider and resource casing', () => {
    const draft = applyDiscogsReleaseToImportDraft({
      artists: [
        {
          id: 'local-robin-stone',
          name: 'Robin Stone',
          type: 'Person',
          aliases: [],
          members: [],
          relationHint: '',
          creditHint: '',
          relations: [],
          credits: [],
          tags: [],
          summary: '',
          externalSources: [
            {
              providerName: 'Discogs',
              resourceType: 'Artist',
              externalId: '111',
              sourceUrl: 'https://www.discogs.com/artist/111',
            },
          ],
        },
      ],
      dictionaries: defaultCatalogDictionaries,
      groups: {
        artists: true,
        classification: false,
        core: false,
        labels: false,
        tracklist: false,
      },
      draft: baseDraft(),
      detail: {
        source: {
          providerName: 'discogs',
          resourceType: 'release',
          externalId: '123',
          sourceUrl: 'https://www.discogs.com/release/123',
          attribution: 'Data provided by Discogs.',
        },
        title: 'Show Me Love',
        artists: ['Robin Stone'],
        year: 1993,
        trackCount: 1,
        labels: [],
        formats: [],
        catalogNumber: null,
        barcodes: [],
        tracklist: [],
        identifiers: [],
        credits: [],
        draft: {
          title: 'Show Me Love',
          type: 'single',
          genres: [],
          year: 1993,
          releaseDate: null,
          artistCredits: [
            {
              name: 'Robin Stone',
              role: 'mainArtist',
              externalSource: {
                providerName: 'discogs',
                resourceType: 'artist',
                externalId: '111',
                sourceUrl: 'https://www.discogs.com/artist/111',
              },
            },
          ],
          labels: [],
          tracklist: [],
          externalSources: [],
        },
      },
    })

    expect(draft.artistCredits).toMatchObject([
      {
        artistId: 'local-robin-stone',
        name: 'Robin Stone',
        role: 'mainArtist',
        externalSource: {
          providerName: 'discogs',
          resourceType: 'artist',
          externalId: '111',
        },
      },
    ])
    expect(draft.selectedArtistIds).toEqual(['local-robin-stone'])
  })
})

function baseDraft(): ReleaseImportDraft {
  return {
    id: 'draft-1',
    sourcePath: '/Music/Release',
    relativePath: 'Release',
    status: 'needsReview',
    title: 'Local Release',
    type: 'single',
    catalogNumber: null,
    labelName: null,
    releaseDate: null,
    year: 1993,
    isVariousArtists: false,
    notOnLabel: true,
    artistNames: [],
    artistCredits: [],
    selectedArtistIds: [],
    artistSuggestions: [],
    labels: [],
    genres: [],
    tags: [],
    externalSources: [],
    coverPath: null,
    issues: [],
    tracks: [],
  }
}
