namespace DiscWeave.Api.Features.Imports;

public sealed record ReleaseImportDraftTrackResponse(
    Guid Id,
    string SourceKind,
    string? FilePath,
    string? RelativePath,
    string? Format,
    long? SizeBytes,
    DateTimeOffset? LastModifiedAt,
    ReleaseImportLocalFileResponse? LocalFile,
    int? DurationSeconds,
    int? Position,
    string? Disc,
    string? Side,
    string Title,
    int? VersionYear,
    IReadOnlyList<string> ArtistNames,
    IReadOnlyList<ReleaseImportArtistCreditResponse> ArtistCredits,
    bool InheritReleaseArtistCredits,
    IReadOnlyList<EntitySuggestionResponse> ArtistSuggestions,
    IReadOnlyList<EntitySuggestionResponse> TrackSuggestions,
    string TrackMode,
    bool IsSkipped,
    Guid? SelectedTrackId,
    IReadOnlyList<Guid> SelectedArtistIds,
    IReadOnlyList<ImportIssueResponse> Issues,
    ReleaseImportFileMoveHintResponse? MoveHint);
